### ISSUE TITLE
Night CI 2023-01-23: Failed to get resource and improve 'GetAllIppool' function.

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1288] opened 2023-01-23 20:31 UTC
action url: https://github.com/spidernet-io/spiderpool/actions/runs/3990196593

```
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0003a7350>: {
          s: "failed to get ippool in subnet",
      }
      failed to get ippool in subnet
  occurred
  In [It] at: /home/runner/work/spiderpool/spiderpool/test/e2e/subnet/subnet_test.go:815 @ 01/23/23 20:31:02.292
```
Occasionally failed to set the correct SpiderSubnet owner ref in the  SpiderIPPool

**Comment by Icarus9913** [comment] 2023-01-28 02:32
The e2e test source codes need to be improved.

https://github.com/spidernet-io/spiderpool/blob/c40f8003405bde8a04e5a54f0fd9f58878165848/test/e2e/common/spidersubnet.go#L261-L269
For the function 'WaitIPPoolNumberInSubnet' to call 'GetIPPoolsInSubnet'.

https://github.com/spidernet-io/spiderpool/blob/c40f8003405bde8a04e5a54f0fd9f58878165848/test/e2e/common/spiderpool.go#L639-L658

If we can not fetch IPPoolList, we should return the nil IPPoolList object. And for the upper function, we need to sleep in the circle loop once we met IPPoolList it nil or IPPoolList.Items are empty.

**Comment by Icarus9913** [comment] 2023-01-28 02:32
cc @ty-dc

**Comment by Icarus9913** [comment] 2023-01-28 03:14
Furthermore，The only way the function 'GetAllIppool' return nil is failing to call 'ListResource' but you do not return the error. You should also improve 'GetAllIppool' function.

https://github.com/spidernet-io/spiderpool/blob/c40f8003405bde8a04e5a54f0fd9f58878165848/test/e2e/common/spiderpool.go#L149-L160

**Comment by ty-dc** [comment] 2023-02-02 03:25
The root cause of the problem is the same as #1274, while e2e also needs to improve the ''GetAllIppool' method', The e2e fix will close this issue, and the root cause of the problem is tracked by #1274.

**Comment by ty-dc** [comment] 2023-02-17 02:19
#1301

**Closed by ty-dc** 2023-02-17 02:19 UTC
Labels: priority/important-longterm, kind/bug
