### ISSUE TITLE
Night CI 2023-01-24: Failed

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1289] opened 2023-01-24 21:25 UTC
action url: https://github.com/spidernet-io/spiderpool/actions/runs/4000065180

**Comment by ty-dc** [comment] 2023-02-02 03:14
Failed to create ippool, the cause of the problem should be a failure to set the owner and label, Same problem as this [one](https://github.com/spidernet-io/spiderpool/issues/1274), I will close this issue and track the resolution by another issue, thanks. cc @iiiceoo

**Closed by ty-dc** 2023-02-02 03:14 UTC
Labels: kind/bug
